### ISSUE TITLE
Where can I find some documentation for this library ?

### ISSUE THREAD

**Issue by yw662** [cloudflare/opaque-ts#9]
I am building a web app on cf pages (with functions) and planning to use the opaque protocol for user registration and authentication. More precisely I am planning to generate signatures on client side (browser side) with the private key of the user so it can be checked server side and by other users.
I have read about the protocol itself but I cannot find examples and documentations on this particular library. Where can I find some ?
And is this library usable on browser side or as cf worker ? And would you recommend this library or opaque-ke + wasm ?

**Comment by armfazh** [comment]
You can take a look at the test script. It runs both registration and login.
https://github.com/cloudflare/opaque-ts/blob/main/test/opaque_full.test.ts#L45

This is Typescript that compiles to JS, so you will be able to run in browser and CF Worker.

This demo shows you it runs ok in the browser: https://opaque-full.research.cloudflare.com/
